dockerize linting task
alpine-hodler/gidari pull request #235
Opened 2022-10-05 06:32 UTC by PankhudiB

Dockerize the linter #223

2022-10-05 06:56 UTC, prestonvasquez requested changes
Outstanding, it works like a charm! Just one suggestion :)

2022-10-05 06:56 UTC, prestonvasquez commented on Makefile
> +	docker rmi -f gidari_lint || true
```suggestion
	docker-compose -f "docker-compose.yml" up -d \
                --remove-orphans \
                --force-recreate \
                --build lint
```

2022-10-05 07:03 UTC, prestonvasquez commented
@PankhudiB Would you mind also updating the docs/CONTRIBUTIONS.md file to remove the golangci-lint dependency requirement?

2022-10-05 11:00 UTC, PankhudiB commented on Makefile
> +	docker rmi -f gidari_lint || true
Thats a nice suggestion. Thank you !

2022-10-05 14:27 UTC, prestonvasquez commented
@PankhudiB Can you resolve the merge conflicts here? Then I can merge the PR.

2022-10-06 17:18 UTC, PankhudiB commented
@prestonvasquez Merged them, can you kindly review it ?

2022-10-07 04:43 UTC, prestonvasquez commented
Sorry for the late reply. Thank you so much for this contribution!

2022-10-07 04:43 UTC, merged